exp: 300_infer_exp000
seed: 1129
debug: false

# 学習expだけ指定
train_exp: 100_train_arcface_exp000
train_output_dir: /mnt/nfs/home/hidebu/study/atmaCup-22-CA-x-atmaCup-3rd/experiment

# preprocess（推論で使うppだけは明示）
pp_exp: 000_prepeocess_ver00
pp_dir: /mnt/nfs/home/hidebu/study/atmaCup-22-CA-x-atmaCup-3rd/data/processed

# 推論だけの設定（trainと独立）
tta_hflip: true
unknown_threshold: 0.815
batch_size: 256
num_workers: 8
device: cuda