exp: 100_train_arcface_exp001
seed: 1129
debug: false

# exp配下に全部入れる
train_output_dir: /mnt/nfs/home/hidebu/study/atmaCup-22-CA-x-atmaCup-3rd/experiment

# preprocess（推論で使うppだけは明示）
pp_exp: 000_prepeocess_ver01
pp_dir: /mnt/nfs/home/hidebu/study/atmaCup-22-CA-x-atmaCup-3rd/data/processed

# 推論設定
tta_hflip: true
batch_size: 256
num_workers: 8
device: cuda

# threshold: 200の結果を読む（おすすめ）
# 200の best_2d.txt を読み込んで unknown_threshold/margin_threshold を自動設定したい場合
load_threshold_from_200: true
threshold_file: best_2d.txt
thr_key: thr_median_nonzero
mthr_key: mthr_median_nonzero # median / median_nonzero
combine_mode: or

# fallback（ファイルが無い場合に備えて一応残す）
unknown_threshold: 0.72
margin_threshold: 0.03

# prototypes 用に clean train を優先する
use_clean_train_csv: true