exp: 100_train_arcface_exp005
seed: 1129
debug: false

train_output_dir: /mnt/nfs/home/hidebu/study/atmaCup-22-CA-x-atmaCup-3rd/experiment

pp_exp: 000_prepeocess_ver01
pp_dir: /mnt/nfs/home/hidebu/study/atmaCup-22-CA-x-atmaCup-3rd/data/processed

tta_hflip: true
batch_size: 256
num_workers: 8
device: cuda

# threshold source
threshold_source: auto   # json -> best_2d -> fallback

# (autoの2番手として) 200の best_2d.txt を読む
load_threshold_from_200: true
threshold_file: best_2d.txt
thr_key: thr_median_nonzero
mthr_key: mthr_median_nonzero
combine_mode: or

# fallback
unknown_threshold: 0.72
margin_threshold: 0.03

use_clean_train_csv: true
infer_name: 300_infer

# classwise
use_classwise_thresholds: true
classwise_apply_mode: looser_sim_only
classwise_use_margin: false
classwise_sim_clip_delta: 0.15 # 0.15
classwise_margin_clip_delta: 0.05

# margin gate
margin_gate_add: 0.10
# margin_gate_sim: null