# ===== General ===== 
exp: 100_train_arcface_exp012 # TODO: 毎回、実験の連番を変える
seed: 626 #1129
# for Debug
debug: false
author: hidebu
# デバイス設定
device: cuda
# WandB設定
use_wandb: true
wandb_project: atmacup22
wandb_run_name: new_atmacup_22  # null の場合は wandb_run_name: null と記述

# ===== data ======
# paths
data_dir: /mnt/nfs/home/hidebu/study/atmaCup-22-CA-x-atmaCup-3rd/data/raw
image_dir: /mnt/nfs/home/hidebu/study/atmaCup-22-CA-x-atmaCup-3rd/data/raw/images
crop_dir: /mnt/nfs/home/hidebu/study/atmaCup-22-CA-x-atmaCup-3rd/data/processed/crops  # trainデータのクロップ画像の保存先
pp_dir: /mnt/nfs/home/hidebu/study/atmaCup-22-CA-x-atmaCup-3rd/data/processed
output_dir: /mnt/nfs/home/hidebu/study/atmaCup-22-CA-x-atmaCup-3rd/experiment
use_crops: true  # 高速読み込みのため事前クロップした画像を使用
# preprocessデータ
pp_exp: 000_prepeocess_ver03
train_pp_csv: /mnt/nfs/home/hidebu/study/atmaCup-22-CA-x-atmaCup-3rd/data/processed/000_prepeocess_ver03/train_meta_pp.csv
test_pp_csv: /mnt/nfs/home/hidebu/study/atmaCup-22-CA-x-atmaCup-3rd/data/processed/000_prepeocess_ver03/test_meta_pp.csv
# drop junk
drop_junk: true
junk_col: is_junk
# oof
oof_tta_hflip: true
# ===== split =====
split_method: sgkf  # holdout / sgkf
val_quarter_from: Q2-016
n_splits: 4
folds: [0,1,2,3]

# ===== model ===== 
# ===== for image ===== 
model_name: efficientnet_b3 # efficientnet_b0 | convnext_tiny | convnext_base | swin_base_patch4_window12_384
num_classes: 11  # label_id 0-10
pretrained: true
img_size: 384 # 224
embedding_dim: 512 # 768 # 512
# ===== tabular features =====
use_tabular: true
num_features:
  - angle_id
  - fx
  - fy
  - dist_center
  - rank_x
  - rank_y
  - rank_x_norm
  - rank_y_norm
  - nn_dist
  - mean_dist
  - shape_scale
  - bbox_area
  - bbox_aspect
  - n_players
# =====  ArcFace設定 ===== 
arcface_s: 30.0
arcface_m: 0.5
# ===== training ===== 
batch_size: 128 # 128
num_workers: 8
epochs: 20
lr: 0.001
weight_decay: 0.0001
ema_decay: 0.995
use_ema: true

# ===== unknown threshold (推論用) =====
unknown_threshold: 0.5

# =========================
# threshold-aware CV (NEW)
# =========================
threshold_cv_enable: true
# 何 epoch ごとに計算するか（毎epochなら 1）
threshold_cv_every_n_epochs: 1
# embedding の hflip TTA（oof と揃えるのが無難）
threshold_cv_tta_hflip: true
# prototype の作り方
# - weights: ArcFace の class weight を prototype とみなす（高速）
# - train  : train全量を舐めて prototype 作る（重いが推論に近い）
threshold_cv_prototype_source: train # weights
# grid search 範囲（とりあえず 200 と同じでもOK）
# 速くしたいなら thr_min を 0.5 くらいに上げるのおすすめ
threshold_cv_thr_min: 0.0
threshold_cv_thr_max: 1.0
threshold_cv_thr_step: 0.01
threshold_cv_mthr_min: 0.0
threshold_cv_mthr_max: 0.10
threshold_cv_mthr_step: 0.005
threshold_cv_combine_mode: or
# pseudo-unknown の対象クラス
threshold_cv_holdout_ids: [0,1,2,3,4,5,6,7,8,9,10] # 3,4,5,6,7,8,9,10
# eval batch size（GPUに余裕があれば増やしてOK）
threshold_cv_batch_size: 256
threshold_cv_num_workers: 8
# json保存（epochごと/best/latest）
threshold_cv_save_json: true

# =========================
# checkpoint / early stop (OPTION)
# =========================
# まずは log だけ見たいなら val_f1 のままでOK
# ckpt_monitor: val_f1
# threshold-aware CV を monitor に使うならこれ
ckpt_monitor: val_thr_cv # val_thr_cv | val_f1
ckpt_mode: max
use_early_stopping: false # true
early_stopping_patience: 5